### ISSUE TITLE
bot offline

### ISSUE THREAD

**Issue by slemetayer** [sofianegargouri/kaamelott-discord-bot#1]
Bonjour, j'ai installer le bot sur mon serveur discord, mais il ne passe pas on line

**Comment by sofianegargouri** [comment]
Hello @slemetayer 
En effet, ça fait un petit moment que je ne l'hébergeais plus. Cependant le code sur GitHub te permet de l'héberger toi-même 😉

**Comment by HugoGresse** [comment]
tristesse :(

**Comment by sofianegargouri** [comment]
> tristesse :(

@HugoGresse Il est de nouveau en ligne du jamais 😉

**Comment by HugoGresse** [comment]
je suis pas sur de bien utiliser le bot: 
`/kaamelott help` ou `/kaamelott random` n'a aucun effet sur un salon textuel, que je sois en audio ou pas.

**Comment by sofianegargouri** [comment]
Les commandes `help` et `random` n'ont pas été remises lors de la migration vers des "slash commands". NOrmalement si tu fais /kmlt ou /kaamelott, Discord doit t'indiquer automatiquement quoi saisir.
Sinon, le /kmlt met un son random. 
La liste des sons est disponible ici: https://github.com/2ec0b4/kaamelott-soundboard/blob/e86e0b65df3713c408b02b3bdafb54b0721c78b4/sounds/sounds.json

N'hésite pas à ouvrir une issue s'il manque des éléments, ou alors ouvrir un pull-request si jamais tu as envie de contribuer 😉

**Comment by HugoGresse** [comment]
non justement, pas d'autocomplete sur discord, aucune des commande ne semble faire quelque chose :(

**Comment by sofianegargouri** [comment]
Même après quelques heures / un redémarrage ?
Discord a pas mal de cache / temps de rollout sur ces commandes, mais de mon côté tout est bon:
![image](https://user-images.githubusercontent.com/4323986/114425677-9a01db00-9bb9-11eb-8b39-be539a707d45.png)

**Comment by HugoGresse** [comment]
Non toujours rien, après reboot ou sur la version web, la commande ne m'est pas proposé :/
